//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_productos
    {
        public int fld_idProducto { get; set; }
        public string fld_nombreProducto { get; set; }
        public decimal fld_precio { get; set; }
        public int fld_cantidad { get; set; }
    }
}
