//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_typeUser
    {
        public tbl_typeUser()
        {
            this.tbl_user = new HashSet<tbl_user>();
        }
    
        public int fld_id { get; set; }
        public string fld_tipo { get; set; }
    
        public virtual ICollection<tbl_user> tbl_user { get; set; }
    }
}
